### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by qassisju** [qassisju/MI-449-SS17-741-css-stealing-styles-xedvDK#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://qassisju.github.io/MI-449-SS17-741-css-stealing-styles-xedvDK/) and meets the following criteria:

- [x] The page includes the name of your search engine in big letters (you can make it up), with a search `input` below it, then a button below that to run the search (the button doesn't have to do anything for this prototype)
- [x] The font size of the search engine name is at least 70 pixels, so that it's very easy to see
- [x] `span` elements are wrapped around each letter of the name, like this: `<span>G</span><span>o</span><span>o</span><span>g</span><span>l</span><span>e</span>`, so that they can be styled individually with classes
- [x] The on-hover colors from the paragraphs [on this page](http://skillful-clouds.surge.sh/) are used to color individual letters of your name (similar to the letters in Google's logo)
- [x] Inspect the `input` element at the bottom of the [_Prototyping states_ page of the lesson](5) to create an identical-looking search box for your own site (it should even use the same styles on `focus`)
- [x] The styles from the "Create Account" button [on this page](http://plant-servant.surge.sh/) are used for your "Search" button (it should even use the same styles on `hover` and `active`)
- [x] There are no stylelint errors in your CSS (this will also be expected for all future projects)
- [x] All your CSS exists in a `.css` file

**Comment by chrisvfritz** [comment]
This is looking really good! 🌟  Only a few areas for improvement:

### `active` style for the button

It looks like the styles for the `active` state of the button are being overridden by the `hover` styles, because they have the same specificity, but the `hover` styles are listed last. 

This causes your code to work a _little_ differently (e.g. the button doesn't shift down when clicking on it). To fix this, you can just move the `active` styles below the `hover` styles. 

Let me know if that makes sense! 😅 

### Variation in default styles between `button` and `a`

You're seeing some slight variation from that other page, because you're using a `button` element while the other page uses an `a` element. To compensate, you can either:

- Also use an `a` element yourself, _OR_
- Update these specific properties:
  - Remove the border with `border: none`
  - Change the mouse cursor with `cursor: pointer`

**Comment by qassisju** [comment]
Check now!!!!!

**Comment by chrisvfritz** [comment]
The first item is looking much better. It looks like you added the `border: none` and `cursor: pointer` to the wrong element though: the `input` rather than the `button`. 🙂

**Comment by qassisju** [comment]
Okay, hopefully that should be fixed

**Comment by chrisvfritz** [comment]
_Almost!_ I'm still seeing the border when the button isn't hovered over.

**Comment by qassisju** [comment]
Done!

**Comment by chrisvfritz** [comment]
Looks good! 👍 :shipit:
